services:
  webapp1:
    build:
      context: .
      dockerfile: WebApp1/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=database;Database=YourDatabase;User Id=sa;Password=YourStrongPassword123!"
    entrypoint: ["./wait-for-it.sh", "database:1433", "--", "dotnet", "WebApp1.dll"]
    networks:
      - app_network

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P YourStrongPassword123! -Q \"SELECT 1\""]
      interval: 30s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  sql_data: